apiVersion: apps/v1
kind: Deployment
metadata:
  name: os2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
        - name: web-container
          image: httpd
          ports:
            - containerPort: 80
