apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-node-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8s-node
  template:
    metadata:
      labels:
        app: k8s-node
    spec:
      containers:
        - name: app
          image: gauravj00/k8s-node-app
          ports:
            - containerPort: 3000
